#! /bin/bash

cp ../../HW2/FirstRoundVisitor.java   ./hw2/FirstRoundVisitor.java 
cp ../../HW2/SecondRoundVisitor.java  ./hw2/SecondRoundVisitor.java 
cp ../../HW2/ThirdRoundVisitor.java   ./hw2/ThirdRoundVisitor.java
cp ../../HW2/Typecheck.java          ./hw2/Typecheck.java 
cp ../../HW2/SymbolTable.java        ./hw2/SymbolTable.java

tar -cvf hw2.tgz ./hw2/FirstRoundVisitor.java ./hw2/SecondRoundVisitor.java ./hw2/ThirdRoundVisitor.java ./hw2/Typecheck.java ./hw2/SymbolTable.java

./run SelfTestCases hw2.tgz 